services:
  redis:
    container_name: redis
    hostname: redis
    image: "redis:alpine"
    ports:
      - "${REDIS_EXPOSE_PORT}:6379"
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: "mongo:latest"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "${MONGODB_EXPOSE_PORT}:27017"
    volumes:
      - mongo_data:/data/db.d
      - ./mongo.d/init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: unless-stopped

  database:
    container_name: database
    hostname: database
    image: 'postgres:15.4'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DATABASE_EXPOSE_PORT}:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./db.d/init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
  database_data:
